name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
      - "prod"
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'


jobs:
  update-prod-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - run: git show --name-only
    - run: git show --name-only origin/prod
    - uses: peter-evans/create-pull-request@v5
      with:
        branch: prod-pr
        base: prod
        title: Update prod
        body: Update the production environment
