name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
      - "prod"
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'


jobs:
  update-prod-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - run: |
        git co -B prod-pr
        gh pr create -B prod -H prod-pr --title 'Merge develop into prod' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
