name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
      - "prod"
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'


jobs:
  update-prod-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: prod-pr
