name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
      - "prod"
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'


jobs:
  update-prod-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - run: git checkout -B prod-pr
    - run: git push --force origin prod-pr
    - run: (gh pr view prod-pr --json state | grep OPEN) || gh pr create -B prod -H prod-pr --title 'deploy the prod environment' --body 'Please review carefully!'
